@echo off
cd /d "%~dp0"
call setup_local_env.bat
if errorlevel 1 (
    pause
    exit /b 1
)
set "PANDORICKKI_PYTHON=%~dp0.venv\Scripts\python.exe"
"%PANDORICKKI_PYTHON%" scripts\runtime_preflight.py
if errorlevel 1 (
    pause
    exit /b 1
)
set PANDORICKKI_NEUROBRAIN_RECEIVER_ENABLED=1
set PANDORICKKI_LIVE_CRYPTO=1
set PANDORICKKI_CRYPTO_LIVE_PRICE_DISPLAY=1
set PANDORICKKI_STOCK_TEST_MODE=0
set PANDORICKKI_STOCK_LIVE_PRICE_DISPLAY=1
set PANDORICKKI_STOCK_DATA_OBSERVER_ENABLED=1
set PANDORICKKI_STOCK_SHADOW_LONG_BULLISH_SCORE=60
set PANDORICKKI_STOCK_SHADOW_SHORT_BULLISH_SCORE=40
set PANDORICKKI_STOCK_SHADOW_RISK_ATR_MULTIPLIER=1
set PANDORICKKI_STOCK_SHADOW_RISK_MINIMUM_DISTANCE_PERCENT=0.5
set PANDORICKKI_STOCK_SHADOW_RISK_TARGET_1_MULTIPLE=1
set PANDORICKKI_STOCK_SHADOW_RISK_TARGET_2_MULTIPLE=2
set PANDORICKKI_STOCK_SHADOW_RISK_TARGET_3_MULTIPLE=3
set PANDORICKKI_STOCK_SHADOW_RISK_PRICE_DECIMALS=4
set PANDORICKKI_TELEGRAM_ENABLED=0
set PANDORICKKI_TELEGRAM_DRY_RUN=1
set PANDORICKKI_DECISION_GATE_OBSERVER_ENABLED=1
set PANDORICKKI_DECISION_GATE_MINIMUM_PROBABILITY=60
set PANDORICKKI_DECISION_GATE_MINIMUM_CONFIDENCE=60
set PANDORICKKI_DECISION_GATE_CONFIDENCE_TOLERANCE=0
start "" http://127.0.0.1:8000
"%PANDORICKKI_PYTHON%" main.py --headless --web
